//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Evol_UI.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Evol_UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;PokeData xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;Venusaur&lt;/Name&gt;
        ///  &lt;Level&gt;50&lt;/Level&gt;
        ///  &lt;HP&gt;158&lt;/HP&gt;
        ///  &lt;Attack&gt;105&lt;/Attack&gt;
        ///  &lt;SpAttack&gt;123&lt;/SpAttack&gt;
        ///  &lt;Defense&gt;106&lt;/Defense&gt;
        ///  &lt;SpDefense&gt;123&lt;/SpDefense&gt;
        ///  &lt;Speed&gt;102&lt;/Speed&gt;
        ///  &lt;Type&gt;GRASS&lt;/Type&gt;
        ///  &lt;Type2&gt;NONE&lt;/Type2&gt;
        ///  &lt;Moves&gt;
        ///    &lt;Move&gt;
        ///      &lt;Power&gt;75&lt;/Power&gt;
        ///      &lt;Accuracy&gt;100&lt;/Accuracy&gt;
        ///      &lt;Special&gt;true&lt;/Special&gt;
        ///      &lt;Type&gt;G [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string _003 {
            get {
                return ResourceManager.GetString("_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;PokeData xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;Charizard&lt;/Name&gt;
        ///  &lt;Level&gt;50&lt;/Level&gt;
        ///  &lt;HP&gt;156&lt;/HP&gt;
        ///  &lt;Attack&gt;107&lt;/Attack&gt;
        ///  &lt;SpAttack&gt;132&lt;/SpAttack&gt;
        ///  &lt;Defense&gt;101&lt;/Defense&gt;
        ///  &lt;SpDefense&gt;108&lt;/SpDefense&gt;
        ///  &lt;Speed&gt;122&lt;/Speed&gt;
        ///  &lt;Type&gt;FIRE&lt;/Type&gt;
        ///  &lt;Type2&gt;NONE&lt;/Type2&gt;
        ///  &lt;Moves&gt;
        ///    &lt;Move&gt;
        ///      &lt;Power&gt;75&lt;/Power&gt;
        ///      &lt;Accuracy&gt;100&lt;/Accuracy&gt;
        ///      &lt;Special&gt;false&lt;/Special&gt;
        ///      &lt;Type&gt; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string _006 {
            get {
                return ResourceManager.GetString("_006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;PokeData xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;Blastoise&lt;/Name&gt;
        ///  &lt;Level&gt;50&lt;/Level&gt;
        ///  &lt;HP&gt;127&lt;/HP&gt;
        ///  &lt;Attack&gt;106&lt;/Attack&gt;
        ///  &lt;SpAttack&gt;108&lt;/SpAttack&gt;
        ///  &lt;Defense&gt;123&lt;/Defense&gt;
        ///  &lt;SpDefense&gt;128&lt;/SpDefense&gt;
        ///  &lt;Speed&gt;100&lt;/Speed&gt;
        ///  &lt;Type&gt;WATER&lt;/Type&gt;
        ///  &lt;Type2&gt;NONE&lt;/Type2&gt;
        ///  &lt;Moves&gt;
        ///    &lt;Move&gt;
        ///      &lt;Power&gt;120&lt;/Power&gt;
        ///      &lt;Accuracy&gt;80&lt;/Accuracy&gt;
        ///      &lt;Special&gt;true&lt;/Special&gt;
        ///      &lt;Type&gt; [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string _009 {
            get {
                return ResourceManager.GetString("_009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;PokeData xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;Arbok&lt;/Name&gt;
        ///  &lt;Level&gt;50&lt;/Level&gt;
        ///  &lt;HP&gt;145&lt;/HP&gt;
        ///  &lt;Attack&gt;116&lt;/Attack&gt;
        ///  &lt;SpAttack&gt;95&lt;/SpAttack&gt;
        ///  &lt;Defense&gt;99&lt;/Defense&gt;
        ///  &lt;SpDefense&gt;109&lt;/SpDefense&gt;
        ///  &lt;Speed&gt;111&lt;/Speed&gt;
        ///  &lt;Type&gt;POISON&lt;/Type&gt;
        ///  &lt;Type2&gt;NONE&lt;/Type2&gt;
        ///  &lt;Moves&gt;
        ///    &lt;Move&gt;
        ///      &lt;Power&gt;90&lt;/Power&gt;
        ///      &lt;Accuracy&gt;100&lt;/Accuracy&gt;
        ///      &lt;Special&gt;true&lt;/Special&gt;
        ///      &lt;Type&gt;POISO [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string _024 {
            get {
                return ResourceManager.GetString("_024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;PokeData xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;Nidoking&lt;/Name&gt;
        ///  &lt;Level&gt;50&lt;/Level&gt;
        ///  &lt;HP&gt;162&lt;/HP&gt;
        ///  &lt;Attack&gt;119&lt;/Attack&gt;
        ///  &lt;SpAttack&gt;111&lt;/SpAttack&gt;
        ///  &lt;Defense&gt;104&lt;/Defense&gt;
        ///  &lt;SpDefense&gt;101&lt;/SpDefense&gt;
        ///  &lt;Speed&gt;111&lt;/Speed&gt;
        ///  &lt;Type&gt;POISON&lt;/Type&gt;
        ///  &lt;Type2&gt;GROUND&lt;/Type2&gt;
        ///  &lt;Moves&gt;
        ///    &lt;Move&gt;
        ///      &lt;Power&gt;65&lt;/Power&gt;
        ///      &lt;Accuracy&gt;100&lt;/Accuracy&gt;
        ///      &lt;Special&gt;false&lt;/Special&gt;
        ///      &lt;Ty [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string _034 {
            get {
                return ResourceManager.GetString("_034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;PokeData xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;Jolteon&lt;/Name&gt;
        ///  &lt;Level&gt;50&lt;/Level&gt;
        ///  &lt;HP&gt;143&lt;/HP&gt;
        ///  &lt;Attack&gt;88&lt;/Attack&gt;
        ///  &lt;SpAttack&gt;83&lt;/SpAttack&gt;
        ///  &lt;Defense&gt;106&lt;/Defense&gt;
        ///  &lt;SpDefense&gt;118&lt;/SpDefense&gt;
        ///  &lt;Speed&gt;152&lt;/Speed&gt;
        ///  &lt;Type&gt;ELECTRIC&lt;/Type&gt;
        ///  &lt;Type2&gt;NONE&lt;/Type2&gt;
        ///  &lt;Moves&gt;
        ///    &lt;Move&gt;
        ///      &lt;Power&gt;120&lt;/Power&gt;
        ///      &lt;Accuracy&gt;50&lt;/Accuracy&gt;
        ///      &lt;Special&gt;true&lt;/Special&gt;
        ///      &lt;Type&gt;E [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string _135 {
            get {
                return ResourceManager.GetString("_135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;PokeData xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;Espeon&lt;/Name&gt;
        ///  &lt;Level&gt;50&lt;/Level&gt;
        ///  &lt;HP&gt;143&lt;/HP&gt;
        ///  &lt;Attack&gt;88&lt;/Attack&gt;
        ///  &lt;SpAttack&gt;153&lt;/SpAttack&gt;
        ///  &lt;Defense&gt;83&lt;/Defense&gt;
        ///  &lt;SpDefense&gt;118&lt;/SpDefense&gt;
        ///  &lt;Speed&gt;132&lt;/Speed&gt;
        ///  &lt;Type&gt;PSYCHIC&lt;/Type&gt;
        ///  &lt;Type2&gt;NONE&lt;/Type2&gt;
        ///  &lt;Moves&gt;
        ///    &lt;Move&gt;
        ///      &lt;Power&gt;65&lt;/Power&gt;
        ///      &lt;Accuracy&gt;100&lt;/Accuracy&gt;
        ///      &lt;Special&gt;true&lt;/Special&gt;
        ///      &lt;Type&gt;PSY [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string _196 {
            get {
                return ResourceManager.GetString("_196", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;PokeData xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;Name&gt;Umbreon&lt;/Name&gt;
        ///  &lt;Level&gt;50&lt;/Level&gt;
        ///  &lt;HP&gt;173&lt;/HP&gt;
        ///  &lt;Attack&gt;88&lt;/Attack&gt;
        ///  &lt;SpAttack&gt;83&lt;/SpAttack&gt;
        ///  &lt;Defense&gt;133&lt;/Defense&gt;
        ///  &lt;SpDefense&gt;153&lt;/SpDefense&gt;
        ///  &lt;Speed&gt;87&lt;/Speed&gt;
        ///  &lt;Type&gt;DARK&lt;/Type&gt;
        ///  &lt;Type2&gt;NONE&lt;/Type2&gt;
        ///  &lt;Moves&gt;
        ///    &lt;Move&gt;
        ///      &lt;Power&gt;60&lt;/Power&gt;
        ///      &lt;Accuracy&gt;0&lt;/Accuracy&gt;
        ///      &lt;Special&gt;false&lt;/Special&gt;
        ///      &lt;Type&gt;DARK&lt;/T [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string _197 {
            get {
                return ResourceManager.GetString("_197", resourceCulture);
            }
        }
    }
}
